export { default as Fixture } from './Fixture'
export type { IFixtureJson } from './Fixture'
export { default as Player } from './Player'
export type { IPlayerJson } from './Player'
export { default as Team } from './Team'
export type { ITeamJson } from './Team'
export { default as Standing } from './Standing'
export type { IStandingJson, IStandingsJson } from './Standing'
export { default as Scorer } from './Scorer'
export type { IScorerJson } from './Scorer'
